In [1]:
pip install pyproj;

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyproj
  Downloading pyproj-3.2.1-cp37-cp37m-manylinux2010_x86_64.whl (6.3 MB)
     |████████████████████████████████| 6.3 MB 3.2 MB/s
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from pyproj) (2022.6.15)
Installing collected packages: pyproj
Successfully installed pyproj-3.2.1

In [2]:
import pandas as pd

In [3]:
ruta = 'https://foscalinternacional.com/datasets/eventos_dengue_2020.csv'
df = pd.read_csv(ruta)

In [4]:
df

,ID,fec_not,semana,año,edad_,uni_med_,sexo_,cod_pais_o,cod_dpto_o,cod_mun_o,...,hipotension,hepatomegalia,hemorragia_mucosa,hipotermia,caida_plaquetas,acum_liquido,aum_hematocrito,conducta,latitud,longitud
0,1,17/01/2020,1,2020,25,1,F,170,68,276,...,2,2,2,2,2,2,2,1. Ambulatorio,7.076011,-73.102501
1,2,10/01/2020,1,2020,24,1,M,170,68,276,...,2,2,2,2,2,2,2,1. Ambulatorio,7.079495,-73.105400
2,3,12/01/2020,1,2020,58,1,M,170,68,276,...,2,2,2,2,2,2,2,1. Ambulatorio,7.090290,-73.091003
3,4,12/01/2020,1,2020,29,1,F,170,68,276,...,2,2,2,2,2,2,2,1. Ambulatorio,7.067435,-73.090958
4,5,10/01/2020,1,2020,56,1,F,170,68,276,...,2,2,2,2,1,2,2,2. Hospitalizacion piso,7.066905,-73.104980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1257,1258,7/03/2020,9,2020,36,1,F,170,68,276,...,2,2,1,2,2,2,2,1. Ambulatorio,7.072610,-73.099487
1258,1259,13/03/2020,9,2020,42,1,M,170,68,276,...,2,2,2,2,1,2,1,2. Hospitalizacion piso,7.065252,-73.103607
1259,1260,8/03/2020,9,2020,2,1,M,170,68,276,...,2,2,2,2,2,2,2,1. Ambulatorio,7.091391,-73.103264
1260,1261,11/03/2020,9,2020,12,1,F,170,68,276,...,2,2,2,2,2,2,2,1. Ambulatorio,7.061083,-73.097000
1261,1262,9/03/2020,9,2020,14,1,M,170,68,276,...,2,2,2,2,2,2,2,2. Hospitalizacion piso,7.062521,-73.080444

In [5]:
from datetime import datetime

df['fec_not2']=pd.to_datetime(df['fec_not'], format="%d/%m/%Y")
df['fecha_contagio2']=pd.to_datetime(df['fecha_contagio'], format="%d/%m/%Y")
df['inicio_sintomas2']=pd.to_datetime(df['inicio_sintomas'], format="%d/%m/%Y")
df['fec_hos_2']=pd.to_datetime(df['fec_hos_'], format="%d/%m/%Y")

In [6]:
import pyproj
P=pyproj.Proj(proj='utm', zone=18, ellps='WGS84', preserve_units=True)

In [7]:
df['x'], df['y']=P(df['latitud'], df['longitud'])
df

,ID,fec_not,semana,año,edad_,uni_med_,sexo_,cod_pais_o,cod_dpto_o,cod_mun_o,...,aum_hematocrito,conducta,latitud,longitud,fec_not2,fecha_contagio2,inicio_sintomas2,fec_hos_2,x,y
0,1,17/01/2020,1,2020,25,1,F,170,68,276,...,2,1. Ambulatorio,7.076011,-73.102501,2020-01-17,2020-01-17,2020-01-10,NaT,2.394617e+06,-9.730308e+06
1,2,10/01/2020,1,2020,24,1,M,170,68,276,...,2,1. Ambulatorio,7.079495,-73.105400,2020-01-10,2020-01-10,2020-01-07,NaT,2.394299e+06,-9.730473e+06
2,3,12/01/2020,1,2020,58,1,M,170,68,276,...,2,1. Ambulatorio,7.090290,-73.091003,2020-01-12,2020-01-12,2020-01-08,NaT,2.396012e+06,-9.730594e+06
3,4,12/01/2020,1,2020,29,1,F,170,68,276,...,2,1. Ambulatorio,7.067435,-73.090958,2020-01-12,2020-01-10,2020-01-06,NaT,2.395905e+06,-9.729826e+06
4,5,10/01/2020,1,2020,56,1,F,170,68,276,...,2,2. Hospitalizacion piso,7.066905,-73.104980,2020-01-10,2020-01-10,2020-01-07,2020-01-10,2.394286e+06,-9.730044e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1257,1258,7/03/2020,9,2020,36,1,F,170,68,276,...,2,1. Ambulatorio,7.072610,-73.099487,2020-03-07,2020-03-06,2020-03-03,NaT,2.394947e+06,-9.730143e+06
1258,1259,13/03/2020,9,2020,42,1,M,170,68,276,...,1,2. Hospitalizacion piso,7.065252,-73.103607,2020-03-13,2020-03-13,2020-03-06,2020-03-13,2.394437e+06,-9.729966e+06
1259,1260,8/03/2020,9,2020,2,1,M,170,68,276,...,2,1. Ambulatorio,7.091391,-73.103264,2020-03-08,2020-03-08,2020-03-04,NaT,2.394604e+06,-9.730836e+06
1260,1261,11/03/2020,9,2020,12,1,F,170,68,276,...,2,1. Ambulatorio,7.061083,-73.097000,2020-03-11,2020-03-11,2020-03-05,NaT,2.395178e+06,-9.729715e+06
1261,1262,9/03/2020,9,2020,14,1,M,170,68,276,...,2,2. Hospitalizacion piso,7.062521,-73.080444,2020-03-09,2020-03-06,2020-03-02,2020-03-06,2.397093e+06,-9.729485e+06

Sacar la distancia de cada punto hasta la alcaldia de Floridablanca, añadiendo una columna

In [18]:
lat_alcaldia = 7.062958503050063
lon_alcaldia = -73.08619741888012

x_alcaldia, y_alcaldia=P(lon_alcaldia, lat_alcaldia)
x_alcaldia, y_alcaldia

(712077.5246709115, 780878.532284854)

(712077.5246709115, 780878.532284854)

In [26]:
from IPython.core.display import Math
from numpy import mat
def distancia(x1,y1,x2,y2):

  d = Math.sqrt(x2-x1)**2+(y2-y1)**2

  return d

  df['distancia'] = [d]

  print(df)